import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Roboto_Mono } from 'next/font/google'


export const metadata: Metadata = {
  title: 'Noticias Argentina / Robotize',
  description: 'Generated by create next app',
}
// const inter = Roboto({ weight: '400',subsets: ['latin'] })
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body>{children}</body> */}
      <body className={roboto_mono.className}>{children}</body>
    </html>
  )
}
